-- Add table for tracking metrics
CREATE TABLE metric (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  published_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  metric VARCHAR(100) NOT NULL,
  amount FLOAT(2) NOT NULL DEFAULT 1.00
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
