# Default configuration for makefile
# Copy this file into Makefile.local

DB_DB = ts2
DB_USER = dayan

# Apache configuration
HTTP_HOSTNAME = collegesailing.org
HTTP_LOGROOT = /var/log/apache2
HTTP_CERTPATH = /etc/apache2/certs/ts2.crt
HTTP_CERTKEYPATH = /etc/apache2/certs/ts2.key

# Conf settings:
#
# MAILTO is the address to send reports
# DLY: daily update frequency, default is every 5 minutes
# WKD: weekend update frequency
CRON_MAILTO = ""
CRON_DLY_FREQ = */5
CRON_WKD_FREQ = 13,43