#!/bin/bash
#
# Use s3cmd to sync public webpages to S3 bucket

cd $(dirname $0)
root=$(hg root)
ping -c 1 www.google.com > /dev/null || exit 2
s3cmd sync --delete-removed "$root/html/" s3://live.collegesailing.org/ > /dev/null || exit 4
